### ISSUE TITLE
latest version is not support Chinese charactors

### ISSUE THREAD

**Issue by fanxi** [nate-parrott/Flashlight#266]

**Comment by nate-parrott** [comment]
Sorry about that! this is an issue that needs to be fixed for individual plugins. I just fixed it for Baidu — which other plugins aren't working?

**Comment by fanxi** [comment]
I test several plugins which for Chinese users, there are all have the same problem. but I find my issue is not appearing in my friend MAC with same version OSX.

**Comment by nate-parrott** [comment]
That's interesting... which plugins are you having trouble with? I think we'll have to fix them individually.

**Comment by fanxi** [comment]
There are only five plugins I had tested, and now there is only one has the issue: youdao.

**Comment by yaoxinghuo** [comment]
Hi, 'large text plugin' also have unicode issue. I have looked into this, but it is complicated for me, can you check and fix that?

**Comment by fanxi** [comment]
I had tested "youdao" "douban" plugins, there are also have Chinese characters problems.

**Comment by czhiling** [comment]
I got the same problem on my macbook air (OSX 10.10.3). Many plugins, even designed for Chinese search engine, such as "jd" for searching on jd.com, a Chinese shopping site, only supports English as a input. However, some of plugins work properly for Chinese input, such as "g 测试“ for googling

**Comment by dobzhao** [comment]
I have some problem when using send_mail plugin.
when using this command
```
attach flashlight.zip to 白芳 with subject here is the file
```
It works just fine.but when using
```
attach flashlight.zip to 白芳 with subject 文件
or 
attach flashlight.zip to 白芳  with subject files saying 中文
```
it doesn't work, hers the error message from flashlightTools, It looks like charset issue, How to fix this?
```
Plugin.py Errors
(None)
Plugin.py run() Errors
Traceback (most recent call last):
  File "/Users/dob/Downloads/FlashlightTool.app/Contents/Frameworks/FlashlightKit.framework/Resources/run_plugin.py", line 9, in <module>
    plugin.run(*input['runArgs'])
  File "/Users/dob/Library/FlashlightPlugins/send_email.bundle/plugin.py", line 61, in run
    send_mail(recips, subject, body, attach)
  File "/Users/dob/Library/FlashlightPlugins/send_email.bundle/send_mail.py", line 30, in send_mail
    """%(asquote(subject), asquote(body), "\n".join(recipient_lines), file_command)
  File "/Users/dob/Library/FlashlightPlugins/send_email.bundle/applescript.py", line 19, in asquote
    return '"{}"'.format(astr)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

Examples.txt Errors
(None)
```
